### ISSUE TITLE
AttributeError: 'Request' object has no attribute 'log'

### ISSUE THREAD

**Issue by tkrevh** [aschn/drf-tracking#27]
If there is a problem with parsing the posted JSON to DRF API endpoint, drf-tracking raises this exception and causes Internal Server Error. Reason is that inside LoggingMixin.initial if there is a ParseError thrown on data_dict = request.data.dict() self.request.log is never set, but finalize_response gets called anyway.

Problem is, you never get to see the actual problem (i.e. `{"detail":"JSON parse error - Expecting property name enclosed in double quotes: line 7 column 1 (char 111)"}`), as the 500 Internal Error masks the problem.

**Comment by on1link** [comment]
Hi, how is the state of this bug, I have problem with this. Thanks

**Comment by bkovacev** [comment]
Hello, I have stumbled upon the same thing on my test suite. I'm testing accessing the given resource without authentication.

```
class DriverReadFailureTests(APITestCase):
    def setUp(self):
        self.client = APIClient()
        self.user = User.objects.create_superuser('admin', 'admin@admin.com', 'admin123')
        self.client.force_login(user=self.user)
        self.token = Token.objects.create(user=self.user)
        self.client.post('/api/drivers/', data=driver_data, format='json')
        self.client.post('/api/drivers/', data=driver_data_second, format='json')
        self.client.logout()

    def test_read_no_auth_driver(self):
        """Try to retrieve json representation of previously added driver.
        """
        response = self.client.get('/api/drivers/')
        self.assertEqual(response.status_code, 401)
```
Traceback:
Error
```
Traceback (most recent call last):
  File "/home/bkovacev/sally-projects/ops4/drivers/tests.py", line 316, in test_read_no_auth_driver
    response = self.client.get('/api/drivers/')
  File "/home/bkovacev/envs/ops4-env/local/lib/python2.7/site-packages/rest_framework/test.py", line 282, in get
    response = super(APIClient, self).get(path, data=data, **extra)
  File "/home/bkovacev/envs/ops4-env/local/lib/python2.7/site-packages/rest_framework/test.py", line 208, in get
    return self.generic('GET', path, **r)
  File "/home/bkovacev/envs/ops4-env/local/lib/python2.7/site-packages/django/test/client.py", line 409, in generic
    return self.request(**r)
  File "/home/bkovacev/envs/ops4-env/local/lib/python2.7/site-packages/rest_framework/test.py", line 279, in request
    return super(APIClient, self).request(**kwargs)
  File "/home/bkovacev/envs/ops4-env/local/lib/python2.7/site-packages/rest_framework/test.py", line 231, in request
    request = super(APIRequestFactory, self).request(**kwargs)
  File "/home/bkovacev/envs/ops4-env/local/lib/python2.7/site-packages/django/test/client.py", line 494, in request
    six.reraise(*exc_info)
  File "/home/bkovacev/envs/ops4-env/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/bkovacev/envs/ops4-env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/bkovacev/envs/ops4-env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/bkovacev/envs/ops4-env/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/bkovacev/envs/ops4-env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/bkovacev/envs/ops4-env/local/lib/python2.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/bkovacev/envs/ops4-env/local/lib/python2.7/site-packages/rest_framework_tracking/mixins.py", line 80, in handle_exception
    self.request.log.errors = traceback.format_exc()
  File "/home/bkovacev/envs/ops4-env/local/lib/python2.7/site-packages/rest_framework/request.py", line 384, in __getattribute__
    six.reraise(info[0], info[1], info[2].tb_next)
  File "<string>", line 2, in reraise
AttributeError: 'Request' object has no attribute 'log'
```

How do I approach this? @avelis @aschn
